language: node_js
node_js:
  - 13

services:
  - docker

script:
  - docker --version
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-frontend:local stevenyirenkyi/udagram-frontend:v1
  - docker tag reverseproxy stevenyirenkyi/reverseproxy:v1
  - docker tag udagram-api-user stevenyirenkyi/udagram-api-user:v1
  - docker tag udagram-api-feed stevenyirenkyi/udagram-api-feed:v1


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push stevenyirenkyi/udagram-frontend:v1
  - docker push stevenyirenkyi/reverseproxy:v1
  - docker push stevenyirenkyi/udagram-api-user/user:v1
  - docker push stevenyirenkyi/udagram-api-feed/user:v1
