apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    run: frontend
spec:
  ports:
  # TODO: CONTAINER NOT CONNECTED TO PORT
  - port: 8100
    targetPort: 80
    protocol: TCP
  selector:
    app: frontend